#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='J3NI'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = '.build'

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx')

def build(bld):
    bld.program(
        source       = ['main.cpp', 'DaemonServer.cpp', 'MsgHandler.cpp', 'IpmiMessage.cpp'],
        target       = 'J3NI',

        includes     = ['.'],
    
        install_path = '../bin'
    )
